// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: goods.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	UserMap       map[string]string      `protobuf:"bytes,3,rep,name=userMap,proto3" json:"userMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoginResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetUserMap() map[string]string {
	if x != nil {
		return x.UserMap
	}
	return nil
}

type GoodsCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=Stock,proto3" json:"Stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsCreateReq) Reset() {
	*x = GoodsCreateReq{}
	mi := &file_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsCreateReq) ProtoMessage() {}

func (x *GoodsCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsCreateReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsCreateReq) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsCreateReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GoodsCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Goods         string                 `protobuf:"bytes,3,opt,name=goods,proto3" json:"goods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsCreateResp) Reset() {
	*x = GoodsCreateResp{}
	mi := &file_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsCreateResp) ProtoMessage() {}

func (x *GoodsCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsCreateResp.ProtoReflect.Descriptor instead.
func (*GoodsCreateResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsCreateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GoodsCreateResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GoodsCreateResp) GetGoods() string {
	if x != nil {
		return x.Goods
	}
	return ""
}

var File_goods_proto protoreflect.FileDescriptor

const file_goods_proto_rawDesc = "" +
	"\n" +
	"\vgoods.proto\x12\x06stream\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\xa7\x01\n" +
	"\tLoginResp\x12\x10\n" +
	"\x03Msg\x18\x01 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x128\n" +
	"\auserMap\x18\x03 \x03(\v2\x1e.stream.LoginResp.UserMapEntryR\auserMap\x1a:\n" +
	"\fUserMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0eGoodsCreateReq\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x02R\x05Price\x12\x14\n" +
	"\x05Stock\x18\x03 \x01(\x03R\x05Stock\"M\n" +
	"\x0fGoodsCreateResp\x12\x10\n" +
	"\x03Msg\x18\x01 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12\x14\n" +
	"\x05goods\x18\x03 \x01(\tR\x05goods2}\n" +
	"\rStreamGreeter\x12,\n" +
	"\x05Login\x12\x10.stream.LoginReq\x1a\x11.stream.LoginResp\x12>\n" +
	"\vGoodsCreate\x12\x16.stream.GoodsCreateReq\x1a\x17.stream.GoodsCreateRespB\x04Z\x02./b\x06proto3"

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData []byte
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)))
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_goods_proto_goTypes = []any{
	(*LoginReq)(nil),        // 0: stream.LoginReq
	(*LoginResp)(nil),       // 1: stream.LoginResp
	(*GoodsCreateReq)(nil),  // 2: stream.GoodsCreateReq
	(*GoodsCreateResp)(nil), // 3: stream.GoodsCreateResp
	nil,                     // 4: stream.LoginResp.UserMapEntry
}
var file_goods_proto_depIdxs = []int32{
	4, // 0: stream.LoginResp.userMap:type_name -> stream.LoginResp.UserMapEntry
	0, // 1: stream.StreamGreeter.Login:input_type -> stream.LoginReq
	2, // 2: stream.StreamGreeter.GoodsCreate:input_type -> stream.GoodsCreateReq
	1, // 3: stream.StreamGreeter.Login:output_type -> stream.LoginResp
	3, // 4: stream.StreamGreeter.GoodsCreate:output_type -> stream.GoodsCreateResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
