// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: cmd/goods.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoodsService_AddCommodities_FullMethodName     = "/ecommerce.GoodsService/AddCommodities"
	GoodsService_UpdateCommodities_FullMethodName  = "/ecommerce.GoodsService/UpdateCommodities"
	GoodsService_DelCommodities_FullMethodName     = "/ecommerce.GoodsService/DelCommodities"
	GoodsService_GetCommoditiesById_FullMethodName = "/ecommerce.GoodsService/GetCommoditiesById"
	GoodsService_SearchCommodities_FullMethodName  = "/ecommerce.GoodsService/SearchCommodities"
	GoodsService_AddGoods_FullMethodName           = "/ecommerce.GoodsService/AddGoods"
	GoodsService_UpdateGoods_FullMethodName        = "/ecommerce.GoodsService/UpdateGoods"
	GoodsService_DelGoods_FullMethodName           = "/ecommerce.GoodsService/DelGoods"
	GoodsService_GetGoodsById_FullMethodName       = "/ecommerce.GoodsService/GetGoodsById"
	GoodsService_SearchGoods_FullMethodName        = "/ecommerce.GoodsService/SearchGoods"
	GoodsService_AddUsers_FullMethodName           = "/ecommerce.GoodsService/AddUsers"
	GoodsService_UpdateUsers_FullMethodName        = "/ecommerce.GoodsService/UpdateUsers"
	GoodsService_DelUsers_FullMethodName           = "/ecommerce.GoodsService/DelUsers"
	GoodsService_GetUsersById_FullMethodName       = "/ecommerce.GoodsService/GetUsersById"
	GoodsService_SearchUsers_FullMethodName        = "/ecommerce.GoodsService/SearchUsers"
)

// GoodsServiceClient is the client API for GoodsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsServiceClient interface {
	// -----------------------commodities-----------------------
	AddCommodities(ctx context.Context, in *AddCommoditiesReq, opts ...grpc.CallOption) (*AddCommoditiesResp, error)
	UpdateCommodities(ctx context.Context, in *UpdateCommoditiesReq, opts ...grpc.CallOption) (*UpdateCommoditiesResp, error)
	DelCommodities(ctx context.Context, in *DelCommoditiesReq, opts ...grpc.CallOption) (*DelCommoditiesResp, error)
	GetCommoditiesById(ctx context.Context, in *GetCommoditiesByIdReq, opts ...grpc.CallOption) (*GetCommoditiesByIdResp, error)
	SearchCommodities(ctx context.Context, in *SearchCommoditiesReq, opts ...grpc.CallOption) (*SearchCommoditiesResp, error)
	// -----------------------goods-----------------------
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
	UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error)
	DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error)
	GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error)
	SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error)
	// -----------------------users-----------------------
	AddUsers(ctx context.Context, in *AddUsersReq, opts ...grpc.CallOption) (*AddUsersResp, error)
	UpdateUsers(ctx context.Context, in *UpdateUsersReq, opts ...grpc.CallOption) (*UpdateUsersResp, error)
	DelUsers(ctx context.Context, in *DelUsersReq, opts ...grpc.CallOption) (*DelUsersResp, error)
	GetUsersById(ctx context.Context, in *GetUsersByIdReq, opts ...grpc.CallOption) (*GetUsersByIdResp, error)
	SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error)
}

type goodsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsServiceClient(cc grpc.ClientConnInterface) GoodsServiceClient {
	return &goodsServiceClient{cc}
}

func (c *goodsServiceClient) AddCommodities(ctx context.Context, in *AddCommoditiesReq, opts ...grpc.CallOption) (*AddCommoditiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCommoditiesResp)
	err := c.cc.Invoke(ctx, GoodsService_AddCommodities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) UpdateCommodities(ctx context.Context, in *UpdateCommoditiesReq, opts ...grpc.CallOption) (*UpdateCommoditiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCommoditiesResp)
	err := c.cc.Invoke(ctx, GoodsService_UpdateCommodities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) DelCommodities(ctx context.Context, in *DelCommoditiesReq, opts ...grpc.CallOption) (*DelCommoditiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelCommoditiesResp)
	err := c.cc.Invoke(ctx, GoodsService_DelCommodities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetCommoditiesById(ctx context.Context, in *GetCommoditiesByIdReq, opts ...grpc.CallOption) (*GetCommoditiesByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommoditiesByIdResp)
	err := c.cc.Invoke(ctx, GoodsService_GetCommoditiesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) SearchCommodities(ctx context.Context, in *SearchCommoditiesReq, opts ...grpc.CallOption) (*SearchCommoditiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCommoditiesResp)
	err := c.cc.Invoke(ctx, GoodsService_SearchCommodities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsResp)
	err := c.cc.Invoke(ctx, GoodsService_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) UpdateGoods(ctx context.Context, in *UpdateGoodsReq, opts ...grpc.CallOption) (*UpdateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoodsResp)
	err := c.cc.Invoke(ctx, GoodsService_UpdateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) DelGoods(ctx context.Context, in *DelGoodsReq, opts ...grpc.CallOption) (*DelGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelGoodsResp)
	err := c.cc.Invoke(ctx, GoodsService_DelGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetGoodsById(ctx context.Context, in *GetGoodsByIdReq, opts ...grpc.CallOption) (*GetGoodsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoodsByIdResp)
	err := c.cc.Invoke(ctx, GoodsService_GetGoodsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) SearchGoods(ctx context.Context, in *SearchGoodsReq, opts ...grpc.CallOption) (*SearchGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGoodsResp)
	err := c.cc.Invoke(ctx, GoodsService_SearchGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) AddUsers(ctx context.Context, in *AddUsersReq, opts ...grpc.CallOption) (*AddUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUsersResp)
	err := c.cc.Invoke(ctx, GoodsService_AddUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) UpdateUsers(ctx context.Context, in *UpdateUsersReq, opts ...grpc.CallOption) (*UpdateUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUsersResp)
	err := c.cc.Invoke(ctx, GoodsService_UpdateUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) DelUsers(ctx context.Context, in *DelUsersReq, opts ...grpc.CallOption) (*DelUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelUsersResp)
	err := c.cc.Invoke(ctx, GoodsService_DelUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetUsersById(ctx context.Context, in *GetUsersByIdReq, opts ...grpc.CallOption) (*GetUsersByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersByIdResp)
	err := c.cc.Invoke(ctx, GoodsService_GetUsersById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) SearchUsers(ctx context.Context, in *SearchUsersReq, opts ...grpc.CallOption) (*SearchUsersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResp)
	err := c.cc.Invoke(ctx, GoodsService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServiceServer is the server API for GoodsService service.
// All implementations must embed UnimplementedGoodsServiceServer
// for forward compatibility.
type GoodsServiceServer interface {
	// -----------------------commodities-----------------------
	AddCommodities(context.Context, *AddCommoditiesReq) (*AddCommoditiesResp, error)
	UpdateCommodities(context.Context, *UpdateCommoditiesReq) (*UpdateCommoditiesResp, error)
	DelCommodities(context.Context, *DelCommoditiesReq) (*DelCommoditiesResp, error)
	GetCommoditiesById(context.Context, *GetCommoditiesByIdReq) (*GetCommoditiesByIdResp, error)
	SearchCommodities(context.Context, *SearchCommoditiesReq) (*SearchCommoditiesResp, error)
	// -----------------------goods-----------------------
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error)
	UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error)
	DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error)
	GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error)
	SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error)
	// -----------------------users-----------------------
	AddUsers(context.Context, *AddUsersReq) (*AddUsersResp, error)
	UpdateUsers(context.Context, *UpdateUsersReq) (*UpdateUsersResp, error)
	DelUsers(context.Context, *DelUsersReq) (*DelUsersResp, error)
	GetUsersById(context.Context, *GetUsersByIdReq) (*GetUsersByIdResp, error)
	SearchUsers(context.Context, *SearchUsersReq) (*SearchUsersResp, error)
	mustEmbedUnimplementedGoodsServiceServer()
}

// UnimplementedGoodsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoodsServiceServer struct{}

func (UnimplementedGoodsServiceServer) AddCommodities(context.Context, *AddCommoditiesReq) (*AddCommoditiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCommodities not implemented")
}
func (UnimplementedGoodsServiceServer) UpdateCommodities(context.Context, *UpdateCommoditiesReq) (*UpdateCommoditiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCommodities not implemented")
}
func (UnimplementedGoodsServiceServer) DelCommodities(context.Context, *DelCommoditiesReq) (*DelCommoditiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelCommodities not implemented")
}
func (UnimplementedGoodsServiceServer) GetCommoditiesById(context.Context, *GetCommoditiesByIdReq) (*GetCommoditiesByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommoditiesById not implemented")
}
func (UnimplementedGoodsServiceServer) SearchCommodities(context.Context, *SearchCommoditiesReq) (*SearchCommoditiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCommodities not implemented")
}
func (UnimplementedGoodsServiceServer) AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedGoodsServiceServer) UpdateGoods(context.Context, *UpdateGoodsReq) (*UpdateGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGoods not implemented")
}
func (UnimplementedGoodsServiceServer) DelGoods(context.Context, *DelGoodsReq) (*DelGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelGoods not implemented")
}
func (UnimplementedGoodsServiceServer) GetGoodsById(context.Context, *GetGoodsByIdReq) (*GetGoodsByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGoodsById not implemented")
}
func (UnimplementedGoodsServiceServer) SearchGoods(context.Context, *SearchGoodsReq) (*SearchGoodsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGoods not implemented")
}
func (UnimplementedGoodsServiceServer) AddUsers(context.Context, *AddUsersReq) (*AddUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUsers not implemented")
}
func (UnimplementedGoodsServiceServer) UpdateUsers(context.Context, *UpdateUsersReq) (*UpdateUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUsers not implemented")
}
func (UnimplementedGoodsServiceServer) DelUsers(context.Context, *DelUsersReq) (*DelUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelUsers not implemented")
}
func (UnimplementedGoodsServiceServer) GetUsersById(context.Context, *GetUsersByIdReq) (*GetUsersByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersById not implemented")
}
func (UnimplementedGoodsServiceServer) SearchUsers(context.Context, *SearchUsersReq) (*SearchUsersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedGoodsServiceServer) mustEmbedUnimplementedGoodsServiceServer() {}
func (UnimplementedGoodsServiceServer) testEmbeddedByValue()                      {}

// UnsafeGoodsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsServiceServer will
// result in compilation errors.
type UnsafeGoodsServiceServer interface {
	mustEmbedUnimplementedGoodsServiceServer()
}

func RegisterGoodsServiceServer(s grpc.ServiceRegistrar, srv GoodsServiceServer) {
	// If the following call panics, it indicates UnimplementedGoodsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoodsService_ServiceDesc, srv)
}

func _GoodsService_AddCommodities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommoditiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).AddCommodities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_AddCommodities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).AddCommodities(ctx, req.(*AddCommoditiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_UpdateCommodities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommoditiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).UpdateCommodities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_UpdateCommodities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).UpdateCommodities(ctx, req.(*UpdateCommoditiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_DelCommodities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCommoditiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).DelCommodities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_DelCommodities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).DelCommodities(ctx, req.(*DelCommoditiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetCommoditiesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommoditiesByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetCommoditiesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_GetCommoditiesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetCommoditiesById(ctx, req.(*GetCommoditiesByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_SearchCommodities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommoditiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).SearchCommodities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_SearchCommodities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).SearchCommodities(ctx, req.(*SearchCommoditiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_UpdateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).UpdateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_UpdateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).UpdateGoods(ctx, req.(*UpdateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_DelGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).DelGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_DelGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).DelGoods(ctx, req.(*DelGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetGoodsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetGoodsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_GetGoodsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetGoodsById(ctx, req.(*GetGoodsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_SearchGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).SearchGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_SearchGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).SearchGoods(ctx, req.(*SearchGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_AddUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).AddUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_AddUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).AddUsers(ctx, req.(*AddUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_UpdateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).UpdateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_UpdateUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).UpdateUsers(ctx, req.(*UpdateUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_DelUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).DelUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_DelUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).DelUsers(ctx, req.(*DelUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetUsersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetUsersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_GetUsersById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetUsersById(ctx, req.(*GetUsersByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).SearchUsers(ctx, req.(*SearchUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsService_ServiceDesc is the grpc.ServiceDesc for GoodsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.GoodsService",
	HandlerType: (*GoodsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCommodities",
			Handler:    _GoodsService_AddCommodities_Handler,
		},
		{
			MethodName: "UpdateCommodities",
			Handler:    _GoodsService_UpdateCommodities_Handler,
		},
		{
			MethodName: "DelCommodities",
			Handler:    _GoodsService_DelCommodities_Handler,
		},
		{
			MethodName: "GetCommoditiesById",
			Handler:    _GoodsService_GetCommoditiesById_Handler,
		},
		{
			MethodName: "SearchCommodities",
			Handler:    _GoodsService_SearchCommodities_Handler,
		},
		{
			MethodName: "AddGoods",
			Handler:    _GoodsService_AddGoods_Handler,
		},
		{
			MethodName: "UpdateGoods",
			Handler:    _GoodsService_UpdateGoods_Handler,
		},
		{
			MethodName: "DelGoods",
			Handler:    _GoodsService_DelGoods_Handler,
		},
		{
			MethodName: "GetGoodsById",
			Handler:    _GoodsService_GetGoodsById_Handler,
		},
		{
			MethodName: "SearchGoods",
			Handler:    _GoodsService_SearchGoods_Handler,
		},
		{
			MethodName: "AddUsers",
			Handler:    _GoodsService_AddUsers_Handler,
		},
		{
			MethodName: "UpdateUsers",
			Handler:    _GoodsService_UpdateUsers_Handler,
		},
		{
			MethodName: "DelUsers",
			Handler:    _GoodsService_DelUsers_Handler,
		},
		{
			MethodName: "GetUsersById",
			Handler:    _GoodsService_GetUsersById_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _GoodsService_SearchUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/goods.proto",
}
