// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: cmd/goods.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------commodities--------------------------------
type Commodities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`       //商品标题
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`       //商品价格
	GoodsImg      string                 `protobuf:"bytes,3,opt,name=goodsImg,proto3" json:"goodsImg,omitempty"` //商品图片
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`         //商品链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commodities) Reset() {
	*x = Commodities{}
	mi := &file_cmd_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commodities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commodities) ProtoMessage() {}

func (x *Commodities) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commodities.ProtoReflect.Descriptor instead.
func (*Commodities) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{0}
}

func (x *Commodities) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Commodities) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Commodities) GetGoodsImg() string {
	if x != nil {
		return x.GoodsImg
	}
	return ""
}

func (x *Commodities) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type AddCommoditiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`       //商品标题
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`       //商品价格
	GoodsImg      string                 `protobuf:"bytes,3,opt,name=goodsImg,proto3" json:"goodsImg,omitempty"` //商品图片
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`         //商品链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommoditiesReq) Reset() {
	*x = AddCommoditiesReq{}
	mi := &file_cmd_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommoditiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommoditiesReq) ProtoMessage() {}

func (x *AddCommoditiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommoditiesReq.ProtoReflect.Descriptor instead.
func (*AddCommoditiesReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{1}
}

func (x *AddCommoditiesReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddCommoditiesReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AddCommoditiesReq) GetGoodsImg() string {
	if x != nil {
		return x.GoodsImg
	}
	return ""
}

func (x *AddCommoditiesReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type AddCommoditiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommoditiesResp) Reset() {
	*x = AddCommoditiesResp{}
	mi := &file_cmd_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommoditiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommoditiesResp) ProtoMessage() {}

func (x *AddCommoditiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommoditiesResp.ProtoReflect.Descriptor instead.
func (*AddCommoditiesResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{2}
}

type UpdateCommoditiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`       //商品标题
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`       //商品价格
	GoodsImg      string                 `protobuf:"bytes,3,opt,name=goodsImg,proto3" json:"goodsImg,omitempty"` //商品图片
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`         //商品链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommoditiesReq) Reset() {
	*x = UpdateCommoditiesReq{}
	mi := &file_cmd_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommoditiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommoditiesReq) ProtoMessage() {}

func (x *UpdateCommoditiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommoditiesReq.ProtoReflect.Descriptor instead.
func (*UpdateCommoditiesReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCommoditiesReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCommoditiesReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UpdateCommoditiesReq) GetGoodsImg() string {
	if x != nil {
		return x.GoodsImg
	}
	return ""
}

func (x *UpdateCommoditiesReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type UpdateCommoditiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommoditiesResp) Reset() {
	*x = UpdateCommoditiesResp{}
	mi := &file_cmd_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommoditiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommoditiesResp) ProtoMessage() {}

func (x *UpdateCommoditiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommoditiesResp.ProtoReflect.Descriptor instead.
func (*UpdateCommoditiesResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{4}
}

type DelCommoditiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCommoditiesReq) Reset() {
	*x = DelCommoditiesReq{}
	mi := &file_cmd_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCommoditiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCommoditiesReq) ProtoMessage() {}

func (x *DelCommoditiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCommoditiesReq.ProtoReflect.Descriptor instead.
func (*DelCommoditiesReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{5}
}

func (x *DelCommoditiesReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelCommoditiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelCommoditiesResp) Reset() {
	*x = DelCommoditiesResp{}
	mi := &file_cmd_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelCommoditiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCommoditiesResp) ProtoMessage() {}

func (x *DelCommoditiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCommoditiesResp.ProtoReflect.Descriptor instead.
func (*DelCommoditiesResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{6}
}

type GetCommoditiesByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommoditiesByIdReq) Reset() {
	*x = GetCommoditiesByIdReq{}
	mi := &file_cmd_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommoditiesByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommoditiesByIdReq) ProtoMessage() {}

func (x *GetCommoditiesByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommoditiesByIdReq.ProtoReflect.Descriptor instead.
func (*GetCommoditiesByIdReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{7}
}

func (x *GetCommoditiesByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommoditiesByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commodities   *Commodities           `protobuf:"bytes,1,opt,name=commodities,proto3" json:"commodities,omitempty"` //commodities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommoditiesByIdResp) Reset() {
	*x = GetCommoditiesByIdResp{}
	mi := &file_cmd_goods_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommoditiesByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommoditiesByIdResp) ProtoMessage() {}

func (x *GetCommoditiesByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommoditiesByIdResp.ProtoReflect.Descriptor instead.
func (*GetCommoditiesByIdResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{8}
}

func (x *GetCommoditiesByIdResp) GetCommodities() *Commodities {
	if x != nil {
		return x.Commodities
	}
	return nil
}

type SearchCommoditiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`        //page
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`      //limit
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`       //商品标题
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`       //商品价格
	GoodsImg      string                 `protobuf:"bytes,5,opt,name=goodsImg,proto3" json:"goodsImg,omitempty"` //商品图片
	Link          string                 `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`         //商品链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommoditiesReq) Reset() {
	*x = SearchCommoditiesReq{}
	mi := &file_cmd_goods_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommoditiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommoditiesReq) ProtoMessage() {}

func (x *SearchCommoditiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommoditiesReq.ProtoReflect.Descriptor instead.
func (*SearchCommoditiesReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCommoditiesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchCommoditiesReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCommoditiesReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchCommoditiesReq) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SearchCommoditiesReq) GetGoodsImg() string {
	if x != nil {
		return x.GoodsImg
	}
	return ""
}

func (x *SearchCommoditiesReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type SearchCommoditiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commodities   []*Commodities         `protobuf:"bytes,1,rep,name=commodities,proto3" json:"commodities,omitempty"` //commodities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommoditiesResp) Reset() {
	*x = SearchCommoditiesResp{}
	mi := &file_cmd_goods_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommoditiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommoditiesResp) ProtoMessage() {}

func (x *SearchCommoditiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommoditiesResp.ProtoReflect.Descriptor instead.
func (*SearchCommoditiesResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCommoditiesResp) GetCommodities() []*Commodities {
	if x != nil {
		return x.Commodities
	}
	return nil
}

// --------------------------------goods--------------------------------
type Goods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`          //标题
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`        //价格
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`         //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_cmd_goods_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{11}
}

func (x *Goods) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Goods) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Goods) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Goods) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Goods) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Goods) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Goods) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`          //标题
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`        //价格
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`         //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsReq) Reset() {
	*x = AddGoodsReq{}
	mi := &file_cmd_goods_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsReq) ProtoMessage() {}

func (x *AddGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsReq.ProtoReflect.Descriptor instead.
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{12}
}

func (x *AddGoodsReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AddGoodsReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AddGoodsReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *AddGoodsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsResp) Reset() {
	*x = AddGoodsResp{}
	mi := &file_cmd_goods_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsResp) ProtoMessage() {}

func (x *AddGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsResp.ProtoReflect.Descriptor instead.
func (*AddGoodsResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{13}
}

type UpdateGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`          //标题
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`        //价格
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`         //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsReq) Reset() {
	*x = UpdateGoodsReq{}
	mi := &file_cmd_goods_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsReq) ProtoMessage() {}

func (x *UpdateGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsReq.ProtoReflect.Descriptor instead.
func (*UpdateGoodsReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGoodsReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UpdateGoodsReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UpdateGoodsReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *UpdateGoodsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoodsResp) Reset() {
	*x = UpdateGoodsResp{}
	mi := &file_cmd_goods_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoodsResp) ProtoMessage() {}

func (x *UpdateGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoodsResp.ProtoReflect.Descriptor instead.
func (*UpdateGoodsResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{15}
}

type DelGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodsReq) Reset() {
	*x = DelGoodsReq{}
	mi := &file_cmd_goods_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsReq) ProtoMessage() {}

func (x *DelGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsReq.ProtoReflect.Descriptor instead.
func (*DelGoodsReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{16}
}

func (x *DelGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelGoodsResp) Reset() {
	*x = DelGoodsResp{}
	mi := &file_cmd_goods_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelGoodsResp) ProtoMessage() {}

func (x *DelGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelGoodsResp.ProtoReflect.Descriptor instead.
func (*DelGoodsResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{17}
}

type GetGoodsByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByIdReq) Reset() {
	*x = GetGoodsByIdReq{}
	mi := &file_cmd_goods_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdReq) ProtoMessage() {}

func (x *GetGoodsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdReq.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{18}
}

func (x *GetGoodsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGoodsByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         *Goods                 `protobuf:"bytes,1,opt,name=goods,proto3" json:"goods,omitempty"` //goods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoodsByIdResp) Reset() {
	*x = GetGoodsByIdResp{}
	mi := &file_cmd_goods_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoodsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsByIdResp) ProtoMessage() {}

func (x *GetGoodsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsByIdResp.ProtoReflect.Descriptor instead.
func (*GetGoodsByIdResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{19}
}

func (x *GetGoodsByIdResp) GetGoods() *Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

type SearchGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`           //page
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`         //limit
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,6,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`          //标题
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`        //价格
	Stock         int64                  `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`         //库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoodsReq) Reset() {
	*x = SearchGoodsReq{}
	mi := &file_cmd_goods_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsReq) ProtoMessage() {}

func (x *SearchGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsReq.ProtoReflect.Descriptor instead.
func (*SearchGoodsReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{20}
}

func (x *SearchGoodsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchGoodsReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchGoodsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchGoodsReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SearchGoodsReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SearchGoodsReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *SearchGoodsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SearchGoodsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type SearchGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goods         []*Goods               `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"` //goods
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoodsResp) Reset() {
	*x = SearchGoodsResp{}
	mi := &file_cmd_goods_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoodsResp) ProtoMessage() {}

func (x *SearchGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoodsResp.ProtoReflect.Descriptor instead.
func (*SearchGoodsResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{21}
}

func (x *SearchGoodsResp) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

// --------------------------------users--------------------------------
type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`    //用户名
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`    //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_cmd_goods_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{22}
}

func (x *Users) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Users) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Users) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Users) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Users) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Users) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AddUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     int64                  `protobuf:"varint,1,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,3,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`    //用户名
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`    //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersReq) Reset() {
	*x = AddUsersReq{}
	mi := &file_cmd_goods_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersReq) ProtoMessage() {}

func (x *AddUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersReq.ProtoReflect.Descriptor instead.
func (*AddUsersReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{23}
}

func (x *AddUsersReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AddUsersReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AddUsersReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *AddUsersReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUsersReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AddUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsersResp) Reset() {
	*x = AddUsersResp{}
	mi := &file_cmd_goods_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsersResp) ProtoMessage() {}

func (x *AddUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsersResp.ProtoReflect.Descriptor instead.
func (*AddUsersResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{24}
}

type UpdateUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`    //用户名
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`    //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersReq) Reset() {
	*x = UpdateUsersReq{}
	mi := &file_cmd_goods_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersReq) ProtoMessage() {}

func (x *UpdateUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersReq.ProtoReflect.Descriptor instead.
func (*UpdateUsersReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateUsersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUsersReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UpdateUsersReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UpdateUsersReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *UpdateUsersReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUsersReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersResp) Reset() {
	*x = UpdateUsersResp{}
	mi := &file_cmd_goods_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersResp) ProtoMessage() {}

func (x *UpdateUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersResp.ProtoReflect.Descriptor instead.
func (*UpdateUsersResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{26}
}

type DelUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUsersReq) Reset() {
	*x = DelUsersReq{}
	mi := &file_cmd_goods_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUsersReq) ProtoMessage() {}

func (x *DelUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUsersReq.ProtoReflect.Descriptor instead.
func (*DelUsersReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{27}
}

func (x *DelUsersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUsersResp) Reset() {
	*x = DelUsersResp{}
	mi := &file_cmd_goods_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUsersResp) ProtoMessage() {}

func (x *DelUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUsersResp.ProtoReflect.Descriptor instead.
func (*DelUsersResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{28}
}

type GetUsersByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdReq) Reset() {
	*x = GetUsersByIdReq{}
	mi := &file_cmd_goods_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdReq) ProtoMessage() {}

func (x *GetUsersByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdReq.ProtoReflect.Descriptor instead.
func (*GetUsersByIdReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{29}
}

func (x *GetUsersByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUsersByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         *Users                 `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"` //users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIdResp) Reset() {
	*x = GetUsersByIdResp{}
	mi := &file_cmd_goods_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIdResp) ProtoMessage() {}

func (x *GetUsersByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIdResp.ProtoReflect.Descriptor instead.
func (*GetUsersByIdResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{30}
}

func (x *GetUsersByIdResp) GetUsers() *Users {
	if x != nil {
		return x.Users
	}
	return nil
}

type SearchUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`           //page
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`         //limit
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`               //id
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //createdAt
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //updatedAt
	DeletedAt     int64                  `protobuf:"varint,6,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //deletedAt
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`    //用户名
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`    //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersReq) Reset() {
	*x = SearchUsersReq{}
	mi := &file_cmd_goods_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReq) ProtoMessage() {}

func (x *SearchUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReq.ProtoReflect.Descriptor instead.
func (*SearchUsersReq) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{31}
}

func (x *SearchUsersReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchUsersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchUsersReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SearchUsersReq) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SearchUsersReq) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *SearchUsersReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchUsersReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SearchUsersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*Users               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` //users
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResp) Reset() {
	*x = SearchUsersResp{}
	mi := &file_cmd_goods_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResp) ProtoMessage() {}

func (x *SearchUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_goods_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResp.ProtoReflect.Descriptor instead.
func (*SearchUsersResp) Descriptor() ([]byte, []int) {
	return file_cmd_goods_proto_rawDescGZIP(), []int{32}
}

func (x *SearchUsersResp) GetUsers() []*Users {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_cmd_goods_proto protoreflect.FileDescriptor

const file_cmd_goods_proto_rawDesc = "" +
	"\n" +
	"\x0fcmd/goods.proto\x12\tecommerce\"i\n" +
	"\vCommodities\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1a\n" +
	"\bgoodsImg\x18\x03 \x01(\tR\bgoodsImg\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\"o\n" +
	"\x11AddCommoditiesReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1a\n" +
	"\bgoodsImg\x18\x03 \x01(\tR\bgoodsImg\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\"\x14\n" +
	"\x12AddCommoditiesResp\"r\n" +
	"\x14UpdateCommoditiesReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1a\n" +
	"\bgoodsImg\x18\x03 \x01(\tR\bgoodsImg\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\"\x17\n" +
	"\x15UpdateCommoditiesResp\"#\n" +
	"\x11DelCommoditiesReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DelCommoditiesResp\"'\n" +
	"\x15GetCommoditiesByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"R\n" +
	"\x16GetCommoditiesByIdResp\x128\n" +
	"\vcommodities\x18\x01 \x01(\v2\x16.ecommerce.CommoditiesR\vcommodities\"\x9c\x01\n" +
	"\x14SearchCommoditiesReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1a\n" +
	"\bgoodsImg\x18\x05 \x01(\tR\bgoodsImg\x12\x12\n" +
	"\x04link\x18\x06 \x01(\tR\x04link\"Q\n" +
	"\x15SearchCommoditiesResp\x128\n" +
	"\vcommodities\x18\x01 \x03(\v2\x16.ecommerce.CommoditiesR\vcommodities\"\xb3\x01\n" +
	"\x05Goods\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x04 \x01(\x03R\tdeletedAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\"\xa9\x01\n" +
	"\vAddGoodsReq\x12\x1c\n" +
	"\tcreatedAt\x18\x01 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x03 \x01(\x03R\tdeletedAt\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\"\x0e\n" +
	"\fAddGoodsResp\"\xbc\x01\n" +
	"\x0eUpdateGoodsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x04 \x01(\x03R\tdeletedAt\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\"\x11\n" +
	"\x0fUpdateGoodsResp\"\x1d\n" +
	"\vDelGoodsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fDelGoodsResp\"!\n" +
	"\x0fGetGoodsByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10GetGoodsByIdResp\x12&\n" +
	"\x05goods\x18\x01 \x01(\v2\x10.ecommerce.GoodsR\x05goods\"\xe6\x01\n" +
	"\x0eSearchGoodsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x06 \x01(\x03R\tdeletedAt\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\t \x01(\x03R\x05stock\"9\n" +
	"\x0fSearchGoodsResp\x12&\n" +
	"\x05goods\x18\x01 \x03(\v2\x10.ecommerce.GoodsR\x05goods\"\xa9\x01\n" +
	"\x05Users\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x04 \x01(\x03R\tdeletedAt\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\x9f\x01\n" +
	"\vAddUsersReq\x12\x1c\n" +
	"\tcreatedAt\x18\x01 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x02 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x03 \x01(\x03R\tdeletedAt\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\x0e\n" +
	"\fAddUsersResp\"\xb2\x01\n" +
	"\x0eUpdateUsersReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x04 \x01(\x03R\tdeletedAt\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\x11\n" +
	"\x0fUpdateUsersResp\"\x1d\n" +
	"\vDelUsersReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x0e\n" +
	"\fDelUsersResp\"!\n" +
	"\x0fGetUsersByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x10GetUsersByIdResp\x12&\n" +
	"\x05users\x18\x01 \x01(\v2\x10.ecommerce.UsersR\x05users\"\xdc\x01\n" +
	"\x0eSearchUsersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tdeletedAt\x18\x06 \x01(\x03R\tdeletedAt\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\"9\n" +
	"\x0fSearchUsersResp\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.ecommerce.UsersR\x05users2\xd5\b\n" +
	"\fGoodsService\x12M\n" +
	"\x0eAddCommodities\x12\x1c.ecommerce.AddCommoditiesReq\x1a\x1d.ecommerce.AddCommoditiesResp\x12V\n" +
	"\x11UpdateCommodities\x12\x1f.ecommerce.UpdateCommoditiesReq\x1a .ecommerce.UpdateCommoditiesResp\x12M\n" +
	"\x0eDelCommodities\x12\x1c.ecommerce.DelCommoditiesReq\x1a\x1d.ecommerce.DelCommoditiesResp\x12Y\n" +
	"\x12GetCommoditiesById\x12 .ecommerce.GetCommoditiesByIdReq\x1a!.ecommerce.GetCommoditiesByIdResp\x12V\n" +
	"\x11SearchCommodities\x12\x1f.ecommerce.SearchCommoditiesReq\x1a .ecommerce.SearchCommoditiesResp\x12;\n" +
	"\bAddGoods\x12\x16.ecommerce.AddGoodsReq\x1a\x17.ecommerce.AddGoodsResp\x12D\n" +
	"\vUpdateGoods\x12\x19.ecommerce.UpdateGoodsReq\x1a\x1a.ecommerce.UpdateGoodsResp\x12;\n" +
	"\bDelGoods\x12\x16.ecommerce.DelGoodsReq\x1a\x17.ecommerce.DelGoodsResp\x12G\n" +
	"\fGetGoodsById\x12\x1a.ecommerce.GetGoodsByIdReq\x1a\x1b.ecommerce.GetGoodsByIdResp\x12D\n" +
	"\vSearchGoods\x12\x19.ecommerce.SearchGoodsReq\x1a\x1a.ecommerce.SearchGoodsResp\x12;\n" +
	"\bAddUsers\x12\x16.ecommerce.AddUsersReq\x1a\x17.ecommerce.AddUsersResp\x12D\n" +
	"\vUpdateUsers\x12\x19.ecommerce.UpdateUsersReq\x1a\x1a.ecommerce.UpdateUsersResp\x12;\n" +
	"\bDelUsers\x12\x16.ecommerce.DelUsersReq\x1a\x17.ecommerce.DelUsersResp\x12G\n" +
	"\fGetUsersById\x12\x1a.ecommerce.GetUsersByIdReq\x1a\x1b.ecommerce.GetUsersByIdResp\x12D\n" +
	"\vSearchUsers\x12\x19.ecommerce.SearchUsersReq\x1a\x1a.ecommerce.SearchUsersRespB\x04Z\x02./b\x06proto3"

var (
	file_cmd_goods_proto_rawDescOnce sync.Once
	file_cmd_goods_proto_rawDescData []byte
)

func file_cmd_goods_proto_rawDescGZIP() []byte {
	file_cmd_goods_proto_rawDescOnce.Do(func() {
		file_cmd_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_goods_proto_rawDesc), len(file_cmd_goods_proto_rawDesc)))
	})
	return file_cmd_goods_proto_rawDescData
}

var file_cmd_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_cmd_goods_proto_goTypes = []any{
	(*Commodities)(nil),            // 0: ecommerce.Commodities
	(*AddCommoditiesReq)(nil),      // 1: ecommerce.AddCommoditiesReq
	(*AddCommoditiesResp)(nil),     // 2: ecommerce.AddCommoditiesResp
	(*UpdateCommoditiesReq)(nil),   // 3: ecommerce.UpdateCommoditiesReq
	(*UpdateCommoditiesResp)(nil),  // 4: ecommerce.UpdateCommoditiesResp
	(*DelCommoditiesReq)(nil),      // 5: ecommerce.DelCommoditiesReq
	(*DelCommoditiesResp)(nil),     // 6: ecommerce.DelCommoditiesResp
	(*GetCommoditiesByIdReq)(nil),  // 7: ecommerce.GetCommoditiesByIdReq
	(*GetCommoditiesByIdResp)(nil), // 8: ecommerce.GetCommoditiesByIdResp
	(*SearchCommoditiesReq)(nil),   // 9: ecommerce.SearchCommoditiesReq
	(*SearchCommoditiesResp)(nil),  // 10: ecommerce.SearchCommoditiesResp
	(*Goods)(nil),                  // 11: ecommerce.Goods
	(*AddGoodsReq)(nil),            // 12: ecommerce.AddGoodsReq
	(*AddGoodsResp)(nil),           // 13: ecommerce.AddGoodsResp
	(*UpdateGoodsReq)(nil),         // 14: ecommerce.UpdateGoodsReq
	(*UpdateGoodsResp)(nil),        // 15: ecommerce.UpdateGoodsResp
	(*DelGoodsReq)(nil),            // 16: ecommerce.DelGoodsReq
	(*DelGoodsResp)(nil),           // 17: ecommerce.DelGoodsResp
	(*GetGoodsByIdReq)(nil),        // 18: ecommerce.GetGoodsByIdReq
	(*GetGoodsByIdResp)(nil),       // 19: ecommerce.GetGoodsByIdResp
	(*SearchGoodsReq)(nil),         // 20: ecommerce.SearchGoodsReq
	(*SearchGoodsResp)(nil),        // 21: ecommerce.SearchGoodsResp
	(*Users)(nil),                  // 22: ecommerce.Users
	(*AddUsersReq)(nil),            // 23: ecommerce.AddUsersReq
	(*AddUsersResp)(nil),           // 24: ecommerce.AddUsersResp
	(*UpdateUsersReq)(nil),         // 25: ecommerce.UpdateUsersReq
	(*UpdateUsersResp)(nil),        // 26: ecommerce.UpdateUsersResp
	(*DelUsersReq)(nil),            // 27: ecommerce.DelUsersReq
	(*DelUsersResp)(nil),           // 28: ecommerce.DelUsersResp
	(*GetUsersByIdReq)(nil),        // 29: ecommerce.GetUsersByIdReq
	(*GetUsersByIdResp)(nil),       // 30: ecommerce.GetUsersByIdResp
	(*SearchUsersReq)(nil),         // 31: ecommerce.SearchUsersReq
	(*SearchUsersResp)(nil),        // 32: ecommerce.SearchUsersResp
}
var file_cmd_goods_proto_depIdxs = []int32{
	0,  // 0: ecommerce.GetCommoditiesByIdResp.commodities:type_name -> ecommerce.Commodities
	0,  // 1: ecommerce.SearchCommoditiesResp.commodities:type_name -> ecommerce.Commodities
	11, // 2: ecommerce.GetGoodsByIdResp.goods:type_name -> ecommerce.Goods
	11, // 3: ecommerce.SearchGoodsResp.goods:type_name -> ecommerce.Goods
	22, // 4: ecommerce.GetUsersByIdResp.users:type_name -> ecommerce.Users
	22, // 5: ecommerce.SearchUsersResp.users:type_name -> ecommerce.Users
	1,  // 6: ecommerce.GoodsService.AddCommodities:input_type -> ecommerce.AddCommoditiesReq
	3,  // 7: ecommerce.GoodsService.UpdateCommodities:input_type -> ecommerce.UpdateCommoditiesReq
	5,  // 8: ecommerce.GoodsService.DelCommodities:input_type -> ecommerce.DelCommoditiesReq
	7,  // 9: ecommerce.GoodsService.GetCommoditiesById:input_type -> ecommerce.GetCommoditiesByIdReq
	9,  // 10: ecommerce.GoodsService.SearchCommodities:input_type -> ecommerce.SearchCommoditiesReq
	12, // 11: ecommerce.GoodsService.AddGoods:input_type -> ecommerce.AddGoodsReq
	14, // 12: ecommerce.GoodsService.UpdateGoods:input_type -> ecommerce.UpdateGoodsReq
	16, // 13: ecommerce.GoodsService.DelGoods:input_type -> ecommerce.DelGoodsReq
	18, // 14: ecommerce.GoodsService.GetGoodsById:input_type -> ecommerce.GetGoodsByIdReq
	20, // 15: ecommerce.GoodsService.SearchGoods:input_type -> ecommerce.SearchGoodsReq
	23, // 16: ecommerce.GoodsService.AddUsers:input_type -> ecommerce.AddUsersReq
	25, // 17: ecommerce.GoodsService.UpdateUsers:input_type -> ecommerce.UpdateUsersReq
	27, // 18: ecommerce.GoodsService.DelUsers:input_type -> ecommerce.DelUsersReq
	29, // 19: ecommerce.GoodsService.GetUsersById:input_type -> ecommerce.GetUsersByIdReq
	31, // 20: ecommerce.GoodsService.SearchUsers:input_type -> ecommerce.SearchUsersReq
	2,  // 21: ecommerce.GoodsService.AddCommodities:output_type -> ecommerce.AddCommoditiesResp
	4,  // 22: ecommerce.GoodsService.UpdateCommodities:output_type -> ecommerce.UpdateCommoditiesResp
	6,  // 23: ecommerce.GoodsService.DelCommodities:output_type -> ecommerce.DelCommoditiesResp
	8,  // 24: ecommerce.GoodsService.GetCommoditiesById:output_type -> ecommerce.GetCommoditiesByIdResp
	10, // 25: ecommerce.GoodsService.SearchCommodities:output_type -> ecommerce.SearchCommoditiesResp
	13, // 26: ecommerce.GoodsService.AddGoods:output_type -> ecommerce.AddGoodsResp
	15, // 27: ecommerce.GoodsService.UpdateGoods:output_type -> ecommerce.UpdateGoodsResp
	17, // 28: ecommerce.GoodsService.DelGoods:output_type -> ecommerce.DelGoodsResp
	19, // 29: ecommerce.GoodsService.GetGoodsById:output_type -> ecommerce.GetGoodsByIdResp
	21, // 30: ecommerce.GoodsService.SearchGoods:output_type -> ecommerce.SearchGoodsResp
	24, // 31: ecommerce.GoodsService.AddUsers:output_type -> ecommerce.AddUsersResp
	26, // 32: ecommerce.GoodsService.UpdateUsers:output_type -> ecommerce.UpdateUsersResp
	28, // 33: ecommerce.GoodsService.DelUsers:output_type -> ecommerce.DelUsersResp
	30, // 34: ecommerce.GoodsService.GetUsersById:output_type -> ecommerce.GetUsersByIdResp
	32, // 35: ecommerce.GoodsService.SearchUsers:output_type -> ecommerce.SearchUsersResp
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cmd_goods_proto_init() }
func file_cmd_goods_proto_init() {
	if File_cmd_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_goods_proto_rawDesc), len(file_cmd_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_goods_proto_goTypes,
		DependencyIndexes: file_cmd_goods_proto_depIdxs,
		MessageInfos:      file_cmd_goods_proto_msgTypes,
	}.Build()
	File_cmd_goods_proto = out.File
	file_cmd_goods_proto_goTypes = nil
	file_cmd_goods_proto_depIdxs = nil
}
